# Generated by Django 5.2.7 on 2025-10-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("documento", models.CharField(max_length=15)),
                ("fecha_de_nacimiento", models.DateField(blank=True, null=True)),
                ("fecha_de_creacion", models.DateTimeField(auto_now_add=True)),
                ("nro_estudiante", models.IntegerField(unique=True)),
            ],
        ),
    ]
