# Generated by Django 5.2.7 on 2025-10-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="nro_telefono",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
    ]
