# Generated by Django 5.2.7 on 2025-11-17 19:33

import cursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cursos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "code",
                    models.CharField(
                        default=cursos.models.generar_code, max_length=32, unique=True
                    ),
                ),
                ("nro_comision", models.IntegerField(unique=True)),
            ],
        ),
    ]
